### ISSUE TITLE
Limitations with <crowd-keypoint> HTML Element in Sagemaker Groundtruth

### ISSUE THREAD

**Issue by gaitanignacio** [aws-samples/amazon-sagemaker-ground-truth-task-uis#15]
## Issue Description

I am currently working with Sagemaker groundtruth for keypoint annotation, and I have encountered an issue with the <crowd-keypoint> HTML element.

When reviewing the documentation at [sms-ui-template-crowd-keypoint](https://docs.aws.amazon.com/sagemaker/latest/dg/sms-ui-template-crowd-keypoint.html), it appears that the base <crowd-keypoint> HTML element was not designed with the most popular keypoint annotation task (e.g. [keypoints-2018](https://cocodataset.org/#keypoints-2018)) in mind. Instead of defining it as a list of objects with a list of different types of keypoints (e.g. multiple instances of humans with a "left_hand", "right_hand", "left_knee", etc.), it is defined as a simple list of keypoints.

The second major issue I have encountered is that I have been testing the usage of the <crowd-keypoint> HTML element, and I have found that it is not possible to move or edit the keypoints if they are preloaded/populated with the initial-value="[]" list.

## Solution

Is there any other HTML/JavaScript example/class created to address this issue, such as "CrowdKeypoint extends HTMLElement" that you can provide access?. This would allow to support the most popular keypoint annotation tasks and enable editing/moving of preloaded keypoints.

Thank you for your attention to this matter.

**Comment by sundargthb** [comment]
Hi @gaitanignacio - Thanks for your question! Unfortunately, with crowd-keypoint, it's not possible directly to bring in pre-labeled/pre-annotated keypoints and adjust them. However, you can use the Video Object Detection - Keypoint modality in SageMaker Ground Truth. By importing images as video frames, you'll be able to move and adjust keypoints as needed.

For a more comprehensive solution, you might want to check out this, by Arthur Putnam - https://github.com/aws-samples/sagemaker-ground-truth-crowd-2d-skeleton-component
