### ISSUE TITLE
Add more than 10 labels for image

### ISSUE THREAD

**Issue by shubhamwagh** [aws-samples/amazon-sagemaker-ground-truth-task-uis#3]
I see that while creating a labeling there is limit of adding up-to 10 labels. How to add more than 10 labels for image?
Let's say I want my images to have 20 labels for semantics. How do I go ahead? Do I have to create multiple jobs?
First job - first 10 labels 
Second job -  remaining 10 labels?

**Comment by samuel-henry** [comment]
Hi Shubham,

The AWS Console limits to 10, but you can create a Labeling Job with > 10 labels if you use the API. 

Thank you,
Sam
